image_root: '/local/scratch3/xfang31/DATA/overallVGIMG'
ann_root: 'annotation'
dense_gt_root: 'annotation/dense_gt'

# set pretrained as a file path or an url
pretrained: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_caption_capfilt_large.pth'

evaluate: False
# size of vit model; base or large
vit: 'base'
vit_grad_ckpt: False
vit_ckpt_layer: 0
batch_size: 2
init_lr: 1e-5

# vit: 'large'
# vit_grad_ckpt: True
# vit_ckpt_layer: 5
# batch_size: 16
# init_lr: 2e-6

image_size: 384

# generation configs
max_length: 20  
min_length: 5
num_beams: 3
prompt: ''

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 20

#mask detect model config
backbone_pretrained: True
feat_size: 4096
hidden_size: 512
max_len: 16
emb_size: 512
rnn_num_layers: 1
vocab_size: 30524 #change this for bert
fusion_type: 'init_inject'
box_detections_per_img: 30 #change this for small sample



